STTMKY STTMNM select /*+ rule */ * 
from SCSCM_ADM.ROTDH ;

SELECT * FROM USRMA;;USERID;

SELECT
    CASE
        WHEN  U.USERID = M.USERID
            THEN  (ROUTKY VALUE_COL,ROUTNM TEXT_COL FROM ROTDH)
        ELSE  "연결 노선코드가 없습니다."
    FROM ROTDH H, RUMAP M, USRMA U    ;
    


SELECT * FROM ROTDH;


SELECT
    CASE WHEN
        (H.ROUTKY AS VALUE_COL,H.ROUTNM AS TEXT_COL 
        FROM ROTDH H, RUMAP M, USRMA U WHERE M.USRID = U.USRID)
    ELSE '연결된 노선코드가없습니다.' 
 
 
 INSERT INTO ROTDH VALUES('TEST','TEST','TEST','TEST','TEST','TEST','TEST','TEST','TEST','TEST',9999999,'TEST','TEST','TEST','TEST','TEST','TEST','TEST');
 COMMIT;
 INSERT INTO RUMAP (USERID, ROUTKY)VALUES('DEV','TEST');
 SELECT * FROM RUMAP;
 
 
SELECT 
NVL(H.ROUTKY AS VALUE_COL,' ')
,NVL(H.ROUTNM AS TEXT_COL,'연결노선이없습니다.')
FROM ROTDH H
LEFT OUTER JOIN RUMAP M
    ON M.ROUTKY = H.ROUTKY
LEFT OUTER JOIN USRMA U
    ON M.USERID = U.USERID;
;