INSERT
		INTO   USRMA 
			(USERID,PASSWD,NMLAST,NMFIRS, 
			 ADDR01,ADDR02,ADDR03,ADDR04, 
			 ADDR05,CITY01,REGN01,POSTCD, 
			 NATNKY,
			 
			 TELN01,TELN02,TELN03, 
			 TLEXT1,FAXTL1,FAXTL2,POBOX1, 
			 POBPC1,EMAIL1,EMAIL2,
			 
			 COMPKY, 
			 DEPART,EMPLID,USERG1,USERG2, 
			 USERG3,USERG4,USERG5,LANGKY, 
			 DATEFM,DATEDL,DECPFM,LLOGID, 
			 LLOGIT,LLOGOD,LLOGOT,MENUKY, 
			 PDAMKY,LLOGWH,TIMFMT,CURRFM,
			 RECNTF,
			 
			 DELMAK,PGSIZE,FTNAME, 
			 FTSIZE,CREDAT,CRETIM,CREUSR, 
			 LMODAT,LMOTIM, LMOUSR,INDBZL, 
			 INDARC,UPDCHK)
		VALUES (
			   #USERID#,
               xx1.enc_varchar2_ins(#PASSWD#,10,'PWD'),
               xx1.enc_varchar2_ins(#NMLAST#, 10, 'NAME'),
               xx1.enc_varchar2_ins(#NMFIRS#, 10, 'NAME'),
               xx1.enc_varchar2_ins(#ADDR01#, 10, 'ADDRESS'),
               
               xx1.enc_varchar2_ins(#ADDR02#, 10, 'ADDRESS'),
               xx1.enc_varchar2_ins(' ', 10, 'ADDRESS'),
               xx1.enc_varchar2_ins(' ', 10, 'ADDRESS'),
               xx1.enc_varchar2_ins(' ', 10, 'ADDRESS'),
               ' ',
               
               ' ',
               xx1.enc_varchar2_ins(#POSTCD#, 10, 'ADDRESS'),               
               'KR',
               
               xx1.enc_varchar2_ins(#TELN01#, 10, 'PHONE'),
               xx1.enc_varchar2_ins(#TELN02#, 10, 'PHONE'),               
               xx1.enc_varchar2_ins(' ', 10, 'PHONE'),
               ' ',
               NVL(#FAXTL1#, ' '),
               ' ',
               xx1.enc_varchar2_ins(' ', 10, 'ADDRESS'),
               xx1.enc_varchar2_ins(' ', 10, 'ADDRESS'),               
               xx1.enc_varchar2_ins('#EMAIL1#', 10, 'MAIL'),
               xx1.enc_varchar2_ins(' ', 10, 'MAIL'),
               
               #COMPKY#,
               NVL(#DEPART#, ' '),
               NVL(#EMPLID#, ' '),               
               NVL(#USERG1#, ' '),
               NVL(#USERG2#, ' '),
               NVL(#USERG3#, ' '),
               NVL(#USERG4#, ' '),
               NVL(#USERG5#, ' '),               
               NVL(#LANGKY#,'KR'),
               '01',
               '20',
               '01',
               NVL(#LLOGID#, ' '),               
               NVL(#LLOGIT#, ' '),
               NVL(#LLOGOD#, ' '),
               NVL(#LLOGOT#, ' '),
               UPPER(#MENUKY#),
               NVL(#PDAMKY#, ' '),               
               NVL(#LLOGWH#, ' '),
               NVL(#TIMFMT#, ' '),
               '10',
               TO_NUMBER(NVL(TRIM(#RECNTF#), 0)),
               
               #DELMAK#,               
               TO_NUMBER(NVL(TRIM(#PGSIZE#), 0)),
               NVL(#FTNAME#,' '),
               TO_NUMBER(NVL(TRIM(#FTSIZE#), 0)),
               TO_CHAR(SYSDATE, 'YYYYMMDD'),
               TO_CHAR(SYSDATE, 'HH24MISS'),               
               #SES_USER_ID#,
 			   TO_CHAR(SYSDATE, 'YYYYMMDD'),
 			   TO_CHAR(SYSDATE, 'HH24MISS'),
 			   #SES_USER_ID#,
               NVL(#INDBZL#, ' '),               
               NVL(#INDARC#, ' '),
               TO_NUMBER(NVL(TRIM(#UPDCHK#), 0))
               )