CREATE OR REPLACE PROCEDURE ch10_exception_proc
IS
    vi_num NUMBER := 0;
BEGIN
    vi_num := 10/0;
    DBMS_OUTPUT.PUT_LINE('Success!');
    
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('오류가 발생했습니다.');
    DBMS_OUTPUT.PUT_LINE('SQL ERROR CODE : '|| SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQL ERROR MESSAGE : '|| SQLERRM); -- 매개변수 없는 SQLERRM
    DBMS_OUTPUT.PUT_LINE(SQLERRM(SQLCODE));
END;    