-- ANSI 내부 조인

-- 기존 문법(ORACLE)
-- SELECT A.컬럼1, A.컬럼2, B.컬럼1, B.컬럼2..
-- FROM 테이블 A, 테이블 B
-- WHERE A.컬럼1 = B.컬럼1 -> 조인 조건
-- ...;

-- ANSI 문법
-- SELECT A.컬럼1, A.컬럼2, B.컬럼1, B.컬럼2...
-- FROM 테이블 A
-- INNER JOIN 테이블 B
--      ON(A.컬럼1 = B.컬럼1) -> 조인 조건
-- WHERE ...;

-- 기존 문법
SELECT A.EMPLOYEE_ID, A.EMP_NAME, B.DEPARTMENT_ID, B.DEPARTMENT_NAME
FROM EMPLOYEES A, DEPARTMENTS B
    WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
    AND A.HIRE_DATE >= TO_DATE('2003-01-01','YYYY-MM-DD');
    
-- ANSI 문법
SELECT A.EMPLOYEE_ID, A.EMP_NAME, DEPARTMENT_ID, B.DEPARTMENT_NAME
FROM EMPLOYEES A
    INNER JOIN DEPARTMENTS B
    USING(DEPARTMENT_ID)
    WHERE A.HIRE_DATE >= TO_DATE('2003-01-01','YYYY-MM-DD');

-- 외부 조인
-- SELECT A.컬럼1, A.ZJFFJA2, B.컬럼1, B.컬럼2...
-- FROM 테이블 A
-- LEFT(RIGHT) [OUTER] JOIN 테이블 B
-- ON (A.컬럼1 = B.컬럼1)
-- WHERE A.컬럼1 = B.컬럼1(+)
-- ...;
SELECT A.EMPLOYEE_ID, A.EMP_NAME, B.JOB_ID, B.DEPARTMENT_ID
FROM EMPLOYEES A
    LEFT OUTER JOIN JOB_HISTORY B
    ON(A.EMPLOYEE_ID = B.EMPLOYEE_ID
        AND A.DEPARTMENT_ID = B.DEPARTMENT_ID);

SELECT A.EMPLOYEE_ID, A.EMP_NAME, B.JOB_ID, B.DEPARTMENT_ID
FROM EMPLOYEES A
    RIGHT OUTER JOIN JOB_HISTORY B
    ON(A.EMPLOYEE_ID = B.EMPLOYEE_ID
        AND A.DEPARTMENT_ID = B.DEPARTMENT_ID);

-- OUTER 생략가능
SELECT A.EMPLOYEE_ID, A.EMP_NAME, B.JOB_ID, B.DEPARTMENT_ID
FROM EMPLOYEES A
LEFT JOIN JOB_HISTORY B
    ON(A.EMPLOYEE_ID = B.EMPLOYEE_ID
        AND A.DEPARTMENT_ID = B.DEPARTMENT_ID);

-- CROSS 조인 = 카타시안 조인
SELECT A.EMPLOYEE_ID, A.EMP_NAME, B.DEPARTMENT_ID, B.DEPARTMENT_NAME
FROM EMPLOYEES A
CROSS JOIN DEPARTMENTS B;

-- FULL OUTER 조인 ANSI만 제공, 양쪽 이가 다 빠진형태도 조회
CREATE TABLE HONG_A(EMP_ID INT);
CREATE TABLE HONG_B(EMP_ID INT);

INSERT INTO HONG_A VALUES (10);
INSERT INTO HONG_A VALUES (20);
INSERT INTO HONG_A VALUES (40);
INSERT INTO HONG_A VALUES (50);

INSERT INTO HONG_B VALUES (10);
INSERT INTO HONG_B VALUES (20);
INSERT INTO HONG_B VALUES (30);

COMMIT;

SELECT * FROM HONG_A;
SELECT * FROM HONG_B;

SELECT A.EMP_ID, B.EMP_ID
FROM HONG_A A, HONG_B B
WHERE A.EMP_ID(+) = B.EMP_ID(+);
-- 외부 조건에서는 한쪽만 (+)를 붙일 수 있다

SELECT A.EMP_ID, B.EMP_ID
FROM HONG_A A
FULL OUTER JOIN HONG_B B
    ON(A.EMP_ID = B.EMP_ID);





